
package views;

import java.util.Calendar;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import models.Funcionario;
import models.Usuario;

import Controller.Controller;
import utils.Utilidades;

/**
 *
 * @author karolyne Marques
 */
public class CadastrarFuncionario extends javax.swing.JDialog {
     Controller controller;
     int id;
     ArrayList<Usuario> usuarios = new ArrayList<>();
     
    /**
     * Creates new form CadastroFuncionario
     */
    public CadastrarFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        controller = new Controller();
        
/*Os códigos de usuário, veiculo, seguro, e locação são gerados automaticamente.
A geração se da por uma contagem, ou seja, se não houver usuário cadastrado
o id gerado será 0 (zero), porém se existir um ou mais usuários na lista
o código gerado será o código do último usuário da lista + 1. A lógica se
aplica aos outros códigos (veiculo, seguro, locação)*/

        this.usuarios = controller.getUsuarios();
        if(!this.usuarios.isEmpty()) {
            this.id = this.usuarios.get(this.usuarios.size()-1).getCodigoUsuario() + 1;
        }
        else {
            this.id = 0;
        }
        
        TextIDFun.setText(Integer.toString(this.id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCadastrarFun = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        LabelCPF = new javax.swing.JLabel();
        TextCPF = new javax.swing.JTextField();
        LabelDataNascimento = new javax.swing.JLabel();
        TextDiaNascimento = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        LabelRG = new javax.swing.JLabel();
        TextRG = new javax.swing.JTextField();
        LabelCEP = new javax.swing.JLabel();
        TextCEP = new javax.swing.JTextField();
        ButtonCancel = new javax.swing.JButton();
        TextEndereco = new javax.swing.JTextField();
        LabelDadosFun = new javax.swing.JLabel();
        ButtonCofirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelIDFun = new javax.swing.JLabel();
        TextIDFun = new javax.swing.JTextField();
        LabelSalario = new javax.swing.JLabel();
        TextPIS = new javax.swing.JTextField();
        LabelPIS = new javax.swing.JLabel();
        Labeladmissao = new javax.swing.JLabel();
        LabelDadosAdmissao = new javax.swing.JLabel();
        TextSalario = new javax.swing.JTextField();
        TextMesNascimento = new javax.swing.JTextField();
        TextAnoNascimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextDiaAdmissao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextMesAdmissao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextAnoAdmissao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Funcionário");
        setResizable(false);

        PanelCadastrarFun.setBackground(new java.awt.Color(255, 255, 255));

        LabelNome.setText("Nome");

        TextNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNome.setMinimumSize(null);
        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });

        LabelCPF.setText("CPF");

        TextCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCPF.setMinimumSize(null);

        LabelDataNascimento.setText("Data de Nasciemento");

        TextDiaNascimento.setText("DD");
        TextDiaNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextDiaNascimento.setMinimumSize(null);
        TextDiaNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDiaNascimentoFocusGained(evt);
            }
        });
        TextDiaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDiaNascimentoActionPerformed(evt);
            }
        });

        LabelEmail.setText("Email");

        TextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEmail.setMinimumSize(null);

        LabelEndereco.setText("Endereço");

        LabelRG.setText("RG");

        TextRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextRG.setMinimumSize(null);

        LabelCEP.setText("CEP");

        TextCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCEP.setMinimumSize(null);
        TextCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCEPActionPerformed(evt);
            }
        });

        ButtonCancel.setBackground(new java.awt.Color(229, 4, 4));
        ButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setText("Cancelar");
        ButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCancel.setBorderPainted(false);
        ButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCancel.setFocusable(false);
        ButtonCancel.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setRequestFocusEnabled(false);
        ButtonCancel.setRolloverEnabled(false);
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        TextEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        LabelDadosFun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosFun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosFun.setText("Dados do Funcionário");
        LabelDadosFun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonCofirm.setBackground(new java.awt.Color(37, 149, 3));
        ButtonCofirm.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCofirm.setText("Confirmar");
        ButtonCofirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCofirm.setBorderPainted(false);
        ButtonCofirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCofirm.setFocusable(false);
        ButtonCofirm.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setRequestFocusEnabled(false);
        ButtonCofirm.setRolloverEnabled(false);
        ButtonCofirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCofirmActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(32, 32, 32));

        LabelIDFun.setText("Código do Funcionário");

        TextIDFun.setEditable(false);
        TextIDFun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextIDFun.setMinimumSize(null);

        LabelSalario.setText("Salário");

        TextPIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextPIS.setMinimumSize(null);

        LabelPIS.setText("PIS");

        Labeladmissao.setText("Data de Admissão");

        LabelDadosAdmissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosAdmissao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosAdmissao.setText("Dados da Admissão");
        LabelDadosAdmissao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TextSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextSalario.setMinimumSize(null);

        TextMesNascimento.setText("MM");
        TextMesNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMesNascimento.setMinimumSize(null);
        TextMesNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextMesNascimentoFocusGained(evt);
            }
        });
        TextMesNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMesNascimentoActionPerformed(evt);
            }
        });

        TextAnoNascimento.setText("AAAA");
        TextAnoNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoNascimento.setMinimumSize(null);
        TextAnoNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAnoNascimentoFocusGained(evt);
            }
        });
        TextAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAnoNascimentoActionPerformed(evt);
            }
        });

        jLabel1.setText("-");

        jLabel2.setText("-");

        TextDiaAdmissao.setText("DD");
        TextDiaAdmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextDiaAdmissao.setMinimumSize(null);
        TextDiaAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDiaAdmissaoFocusGained(evt);
            }
        });
        TextDiaAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDiaAdmissaoActionPerformed(evt);
            }
        });

        jLabel5.setText("-");

        TextMesAdmissao.setText("MM");
        TextMesAdmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMesAdmissao.setMinimumSize(null);
        TextMesAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextMesAdmissaoFocusGained(evt);
            }
        });
        TextMesAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMesAdmissaoActionPerformed(evt);
            }
        });

        jLabel6.setText("-");

        TextAnoAdmissao.setText("AAAA");
        TextAnoAdmissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoAdmissao.setMinimumSize(null);
        TextAnoAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAnoAdmissaoFocusGained(evt);
            }
        });
        TextAnoAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAnoAdmissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastrarFunLayout = new javax.swing.GroupLayout(PanelCadastrarFun);
        PanelCadastrarFun.setLayout(PanelCadastrarFunLayout);
        PanelCadastrarFunLayout.setHorizontalGroup(
            PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelDadosFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                        .addComponent(LabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(54, 54, 54))
                                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelRG, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(TextRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                                .addComponent(TextDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextAnoNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDadosAdmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(LabelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextPIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LabelPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Labeladmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                                .addComponent(TextDiaAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextMesAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextAnoAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextIDFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelIDFun, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarFunLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        PanelCadastrarFunLayout.setVerticalGroup(
            PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarFunLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LabelIDFun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDFun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDadosFun)
                    .addComponent(LabelDadosAdmissao))
                .addGap(18, 18, 18)
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCPF)
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelPIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastrarFunLayout.createSequentialGroup()
                        .addComponent(LabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextDiaAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextMesAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextAnoAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))))
                    .addComponent(Labeladmissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(PanelCadastrarFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCadastrarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCadastrarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm(){
        TextNome.setText("");
        TextCPF.setText("");
        TextRG.setText("");
        TextCEP.setText("");      
        TextEndereco.setText("");       
        TextEmail.setText("");        
        TextSalario.setText("");        
        TextPIS.setText("");   

        TextDiaNascimento.setText("DD");
        TextMesNascimento.setText("MM");        
        TextAnoNascimento.setText("AAAA");   

        TextDiaAdmissao.setText("DD");        
        TextMesAdmissao.setText("MM");        
        TextAnoAdmissao.setText("AAAA");

        this.id = this.usuarios.get(this.usuarios.size()-1).getCodigoUsuario() + 1;
        TextIDFun.setText(Integer.toString(this.id));
    }
    
    private void TextDiaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDiaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDiaNascimentoActionPerformed

    private void TextCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCEPActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void ButtonCofirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCofirmActionPerformed
        // TODO add your handling code here:
        String nome = TextNome.getText();
        String cpf = TextCPF.getText();
        String rg = TextRG.getText();
        String cep = TextCEP.getText();
        String endereco = TextEndereco.getText();
        String email = TextEmail.getText();
        String salario =  TextSalario.getText();
        String pis = TextPIS.getText();
        
        String diaNascimento = TextDiaNascimento.getText();
        String mesNascimento = TextMesNascimento.getText();
        String anoNascimento = TextAnoNascimento.getText();

        String diaAdmissao = TextDiaAdmissao.getText();
        String mesAdmissao = TextMesAdmissao.getText();
        String anoAdmissao = TextAnoAdmissao.getText();
        
        String[] itens = {
        nome,
        cpf,
        rg,
        cep,
        endereco,
        email,
        salario,
        pis,
        diaNascimento,
        mesNascimento, 
        anoNascimento,
        diaAdmissao,
        mesAdmissao,
        anoAdmissao
        };
        
        if(!Utilidades.hasNull(itens)){
            Calendar dataNascimento = Utilidades.getValidDate(diaNascimento, mesNascimento, anoNascimento);
            Calendar dataAdmissao = Utilidades.getValidDate(diaAdmissao, mesAdmissao, anoAdmissao);
            
            if(dataNascimento != null && dataAdmissao != null){
                
                try {
                Usuario f = new Funcionario(
                    this.id,
                    nome,
                    cpf,
                    rg, 
                    dataNascimento, 
                    endereco, 
                    cep, 
                    email, 
                    Float.parseFloat(salario), 
                    pis, 
                    dataAdmissao);

                controller.addUsuario(f);
                this.usuarios.add(f);
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado."
                        + " Funcionário cadastrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                clearForm();
                        
                } catch(NumberFormatException nfe){
                    System.out.println(nfe);

                    JOptionPane.showMessageDialog(this, "Dados inválidos."
                        + " Entradas para salário devem ter o formato: 1111.111,"
                        + " e entradas de data devem ser valores inteiros!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
                } //tryCatch
            } //if validDate
            else {
                JOptionPane.showMessageDialog(this, "Data inválida."
                        + " Dia, mês ou ano inserido são inválidos!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } //if hasNull
        else {
            JOptionPane.showMessageDialog(this, "Entrada de dado vazia."
                    + " Por favor preencha todos os campos!",
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_ButtonCofirmActionPerformed

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void TextMesNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMesNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMesNascimentoActionPerformed

    private void TextAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAnoNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAnoNascimentoActionPerformed

    private void TextDiaAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDiaAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDiaAdmissaoActionPerformed

    private void TextMesAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMesAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMesAdmissaoActionPerformed

    private void TextAnoAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAnoAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAnoAdmissaoActionPerformed

    private void TextDiaNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDiaNascimentoFocusGained
        // TODO add your handling code here:
        if(TextDiaNascimento.getText().equals("DD")){
            TextDiaNascimento.setText("");
        }
    }//GEN-LAST:event_TextDiaNascimentoFocusGained

    private void TextMesNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextMesNascimentoFocusGained
        // TODO add your handling code here:
        if(TextMesNascimento.getText().equals("MM")){
            TextMesNascimento.setText("");
        }
    }//GEN-LAST:event_TextMesNascimentoFocusGained

    private void TextAnoNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAnoNascimentoFocusGained
        // TODO add your handling code here:
        if(TextAnoNascimento.getText().equals("AAAA")){
            TextAnoNascimento.setText("");
        }
    }//GEN-LAST:event_TextAnoNascimentoFocusGained

    private void TextDiaAdmissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDiaAdmissaoFocusGained
        // TODO add your handling code here:
        if(TextDiaAdmissao.getText().equals("DD")){
            TextDiaAdmissao.setText("");
        }
    }//GEN-LAST:event_TextDiaAdmissaoFocusGained

    private void TextMesAdmissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextMesAdmissaoFocusGained
        // TODO add your handling code here:
         if(TextMesAdmissao.getText().equals("MM")){
            TextMesAdmissao.setText("");
        }
    }//GEN-LAST:event_TextMesAdmissaoFocusGained

    private void TextAnoAdmissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAnoAdmissaoFocusGained
        // TODO add your handling code here:
         if(TextAnoAdmissao.getText().equals("AAAA")){
            TextAnoAdmissao.setText("");
        }
    }//GEN-LAST:event_TextAnoAdmissaoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarFuncionario dialog = new CadastrarFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCofirm;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelDadosAdmissao;
    private javax.swing.JLabel LabelDadosFun;
    private javax.swing.JLabel LabelDataNascimento;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelIDFun;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelPIS;
    private javax.swing.JLabel LabelRG;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JLabel Labeladmissao;
    private javax.swing.JPanel PanelCadastrarFun;
    private javax.swing.JTextField TextAnoAdmissao;
    private javax.swing.JTextField TextAnoNascimento;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextDiaAdmissao;
    private javax.swing.JTextField TextDiaNascimento;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextIDFun;
    private javax.swing.JTextField TextMesAdmissao;
    private javax.swing.JTextField TextMesNascimento;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextPIS;
    private javax.swing.JTextField TextRG;
    private javax.swing.JTextField TextSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
