
package views;

import Controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.Veiculo;
import models.VeiculoImportado;
import models.VeiculoNacional;
import utils.Utilidades;

/**
 *
 * @author karolyne Marques
 */
public class CadastrarCarro extends javax.swing.JDialog {
    Controller controller;
    int id;
    ArrayList<Veiculo> veiculos = new ArrayList<>();
    
    /**
     * Creates new form CadastrarCarro
     */
    public CadastrarCarro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new Controller();
        
/*Os códigos de usuário, veiculo, seguro, e locação são gerados automaticamente.
A geração se da por uma contagem, ou seja, se não houver usuário cadastrado
o id gerado será 0 (zero), porém se existir um ou mais usuários na lista
o código gerado será o código do último usuário da lista + 1. A lógica se
aplica aos outros códigos (veiculo, seguro, locação)*/

        this.veiculos = controller.getVeiculos();
        if(!this.veiculos.isEmpty()) {
            this.id = this.veiculos.get(this.veiculos.size()-1).getCodigoVeiculo() + 1;
        }
        else {
            this.id = 0;
        }
        TextIDCarro.setText(Integer.toString(this.id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        PanelCadastrarCarro = new javax.swing.JPanel();
        LabelModelo = new javax.swing.JLabel();
        TextModelo = new javax.swing.JTextField();
        LabelMontadora = new javax.swing.JLabel();
        TextMontadora = new javax.swing.JTextField();
        LabelAnoFabricacao = new javax.swing.JLabel();
        TextAnoFabricacao = new javax.swing.JTextField();
        LabelAnoModelo = new javax.swing.JLabel();
        TextAnoModelo = new javax.swing.JTextField();
        LabelPlaca = new javax.swing.JLabel();
        LabelCategoria = new javax.swing.JLabel();
        TextCategoria = new javax.swing.JTextField();
        LabelValorDiaria = new javax.swing.JLabel();
        TextValorFipe = new javax.swing.JTextField();
        ButtonCancel = new javax.swing.JButton();
        TextPlaca = new javax.swing.JTextField();
        LabelDadosCarro = new javax.swing.JLabel();
        ButtonCofirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelIDCarro = new javax.swing.JLabel();
        TextIDCarro = new javax.swing.JTextField();
        RadioButtonVeiculoImportado = new javax.swing.JRadioButton();
        RadioButtonVeiculoNacional = new javax.swing.JRadioButton();
        LabelTaxaEstadual = new javax.swing.JLabel();
        LabelTaxaFederal = new javax.swing.JLabel();
        TextTaxaEstadual = new javax.swing.JTextField();
        TextTaxaFederal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Carro");
        setResizable(false);

        PanelCadastrarCarro.setBackground(new java.awt.Color(255, 255, 255));

        LabelModelo.setText("Modelo");

        TextModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextModelo.setMinimumSize(null);

        LabelMontadora.setText("Montadora");

        TextMontadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMontadora.setMinimumSize(null);

        LabelAnoFabricacao.setText("Ano de Fabricação");

        TextAnoFabricacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoFabricacao.setMinimumSize(null);

        LabelAnoModelo.setText("Ano do Modelo");

        TextAnoModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoModelo.setMinimumSize(null);

        LabelPlaca.setText("Placa");

        LabelCategoria.setText("Categoria");

        TextCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCategoria.setMinimumSize(null);

        LabelValorDiaria.setText("Valor Fipe");

        TextValorFipe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextValorFipe.setMinimumSize(null);

        ButtonCancel.setBackground(new java.awt.Color(229, 4, 4));
        ButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setText("Cancelar");
        ButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCancel.setBorderPainted(false);
        ButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCancel.setFocusable(false);
        ButtonCancel.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setRequestFocusEnabled(false);
        ButtonCancel.setRolloverEnabled(false);
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        TextPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPlacaActionPerformed(evt);
            }
        });

        LabelDadosCarro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosCarro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosCarro.setText("Dados do Carro");
        LabelDadosCarro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonCofirm.setBackground(new java.awt.Color(37, 149, 3));
        ButtonCofirm.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCofirm.setText("Confirmar");
        ButtonCofirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCofirm.setBorderPainted(false);
        ButtonCofirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCofirm.setFocusable(false);
        ButtonCofirm.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setRequestFocusEnabled(false);
        ButtonCofirm.setRolloverEnabled(false);
        ButtonCofirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCofirmActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(32, 32, 32));

        LabelIDCarro.setText("Código do Veículo");

        TextIDCarro.setEditable(false);
        TextIDCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextIDCarro.setMinimumSize(null);

        buttonGroup.add(RadioButtonVeiculoImportado);
        RadioButtonVeiculoImportado.setText("Veículo Importado");
        RadioButtonVeiculoImportado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonVeiculoImportadoActionPerformed(evt);
            }
        });

        buttonGroup.add(RadioButtonVeiculoNacional);
        RadioButtonVeiculoNacional.setSelected(true);
        RadioButtonVeiculoNacional.setText("Veículo Nacional");
        RadioButtonVeiculoNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonVeiculoNacionalActionPerformed(evt);
            }
        });

        LabelTaxaEstadual.setText("Taxa Imposto Estadual");

        LabelTaxaFederal.setText("Taxa Imposto Federal");

        TextTaxaEstadual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextTaxaEstadual.setMinimumSize(null);

        TextTaxaFederal.setEditable(false);
        TextTaxaFederal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextTaxaFederal.setMinimumSize(null);

        javax.swing.GroupLayout PanelCadastrarCarroLayout = new javax.swing.GroupLayout(PanelCadastrarCarro);
        PanelCadastrarCarro.setLayout(PanelCadastrarCarroLayout);
        PanelCadastrarCarroLayout.setHorizontalGroup(
            PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                        .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextValorFipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextMontadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextPlaca)
                                        .addComponent(LabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarCarroLayout.createSequentialGroup()
                                            .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TextAnoFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LabelAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(TextAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarCarroLayout.createSequentialGroup()
                                                    .addGap(20, 20, 20)
                                                    .addComponent(LabelAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(LabelValorDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelMontadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LabelDadosCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                                .addComponent(RadioButtonVeiculoImportado)
                                                .addGap(25, 25, 25)
                                                .addComponent(RadioButtonVeiculoNacional))
                                            .addComponent(LabelTaxaEstadual)
                                            .addComponent(LabelTaxaFederal)
                                            .addComponent(TextTaxaEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextTaxaFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextIDCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelIDCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        PanelCadastrarCarroLayout.setVerticalGroup(
            PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarCarroLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LabelIDCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDadosCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                        .addComponent(TextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelMontadora))
                    .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioButtonVeiculoImportado)
                        .addComponent(RadioButtonVeiculoNacional)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                        .addComponent(TextMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelValorDiaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextValorFipe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAnoFabricacao)
                            .addComponent(LabelAnoModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(LabelPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastrarCarroLayout.createSequentialGroup()
                        .addComponent(LabelTaxaEstadual)
                        .addGap(14, 14, 14)
                        .addComponent(TextTaxaEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(LabelTaxaFederal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextTaxaFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelCadastrarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCadastrarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCadastrarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm(){
        TextModelo.setText("");
        TextMontadora.setText("");
        TextCategoria.setText("");
        TextValorFipe.setText("");
        TextAnoFabricacao.setText("");
        TextAnoModelo.setText("");      
        TextPlaca.setText("");        
        TextTaxaEstadual.setText("");        
        TextTaxaFederal.setText("");       

        this.id = this.veiculos.get(this.veiculos.size()-1).getCodigoVeiculo() + 1;
        TextIDCarro.setText(Integer.toString(this.id));
    }
    
    private void ButtonCofirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCofirmActionPerformed
        // TODO add your handling code here:
        String modelo = TextModelo.getText();
        String montadora = TextMontadora.getText();
        String categoria = TextCategoria.getText();
        String valorFipe = TextValorFipe.getText();
        String anoFabricacao = TextAnoFabricacao.getText();
        String anoModelo = TextAnoModelo.getText();
        String placa = TextPlaca.getText();
        String taxaEstadual = TextTaxaEstadual.getText();
        String taxaFederal = TextTaxaFederal.getText();
        
        String[] itens = {
            modelo,
            montadora,
            categoria,
            valorFipe,
            anoFabricacao,
            anoModelo,
            placa,
            taxaEstadual,
            (RadioButtonVeiculoImportado.isSelected()?taxaFederal:"1")
        };
        
        if(!Utilidades.hasNull(itens)){
            
            if(anoModelo.length() == 4 && anoFabricacao.length() == 4){ //verificar validade ano
                
                try {
                Veiculo v;
                
                if(RadioButtonVeiculoImportado.isSelected()){
                    v = new VeiculoImportado(
                        this.id,
                        modelo,
                        montadora,
                        Integer.parseInt(anoFabricacao),
                        Integer.parseInt(anoModelo),
                        placa,
                        categoria,
                        Float.parseFloat(valorFipe),
                        Float.parseFloat(taxaEstadual),
                        Float.parseFloat(taxaFederal)
                    );
                }
                else {
                    v = new VeiculoNacional(
                        this.id,
                        modelo,
                        montadora,
                        Integer.parseInt(anoFabricacao),
                        Integer.parseInt(anoModelo),
                        placa,
                        categoria,
                        Float.parseFloat(valorFipe),
                        Float.parseFloat(taxaEstadual)
                    );
                }
                controller.addVeiculo(v);
                this.veiculos.add(v);
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado."
                        + " Veículo cadastrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                clearForm();

                } catch(NumberFormatException nfe){
                    System.out.println(nfe);

                    JOptionPane.showMessageDialog(this, "Dados inválidos."
                        + " Entradas para valor de Fipe devem ter o formato: 1111.111,"
                        + " e entradas de data devem ser valores inteiros!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
                } //tryCatch
            } //if validDate
            else {
                JOptionPane.showMessageDialog(this, "Data inválida."
                        + " Ano de fabricação ou do modelo inserido são inválidos!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } //if hasNull
        else {
            JOptionPane.showMessageDialog(this, "Entrada de dado vazia."
                    + " Por favor preencha todos os campos!",
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonCofirmActionPerformed

    private void TextPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPlacaActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void RadioButtonVeiculoImportadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonVeiculoImportadoActionPerformed
        // TODO add your handling code here:
        TextTaxaFederal.setEditable(true);
    }//GEN-LAST:event_RadioButtonVeiculoImportadoActionPerformed

    private void RadioButtonVeiculoNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonVeiculoNacionalActionPerformed
        // TODO add your handling code here:
        TextTaxaFederal.setEditable(false);
    }//GEN-LAST:event_RadioButtonVeiculoNacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarCarro dialog = new CadastrarCarro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCofirm;
    private javax.swing.JLabel LabelAnoFabricacao;
    private javax.swing.JLabel LabelAnoModelo;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelDadosCarro;
    private javax.swing.JLabel LabelIDCarro;
    private javax.swing.JLabel LabelModelo;
    private javax.swing.JLabel LabelMontadora;
    private javax.swing.JLabel LabelPlaca;
    private javax.swing.JLabel LabelTaxaEstadual;
    private javax.swing.JLabel LabelTaxaFederal;
    private javax.swing.JLabel LabelValorDiaria;
    private javax.swing.JPanel PanelCadastrarCarro;
    private javax.swing.JRadioButton RadioButtonVeiculoImportado;
    private javax.swing.JRadioButton RadioButtonVeiculoNacional;
    private javax.swing.JTextField TextAnoFabricacao;
    private javax.swing.JTextField TextAnoModelo;
    private javax.swing.JTextField TextCategoria;
    private javax.swing.JTextField TextIDCarro;
    private javax.swing.JTextField TextModelo;
    private javax.swing.JTextField TextMontadora;
    private javax.swing.JTextField TextPlaca;
    private javax.swing.JTextField TextTaxaEstadual;
    private javax.swing.JTextField TextTaxaFederal;
    private javax.swing.JTextField TextValorFipe;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
