
package views;

import Controller.Controller;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import models.Cliente;
import models.Usuario;
import utils.Utilidades;

/**
 *
 * @author karolyne Marques
 */
public class CadastrarCliente extends javax.swing.JDialog {
    Controller controller;
    int id;
    
    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new Controller();
        
/*Os códigos de usuário, veiculo, seguro, e locação são gerados automaticamente.
A geração se da por uma contagem, ou seja, se não houver usuário cadastrado
o id gerado será 0 (zero), porém se existir um ou mais usuários na lista
o código gerado será o código do último usuário da lista + 1. A lógica se
aplica aos outros códigos (veiculo, seguro, locação)*/

        ArrayList<Usuario> usuarios = controller.getUsuarios();
        if(!usuarios.isEmpty()) {
            id = usuarios.get(usuarios.size()-1).getCodigoUsuario() + 1;
        }
        else {
            id = 0;
        }
        
        TextIDCliente.setText(Integer.toString(id));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCadastrarCliente = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        LabelCPF = new javax.swing.JLabel();
        TextCPF = new javax.swing.JTextField();
        LabelDataNascimento = new javax.swing.JLabel();
        TextDiaNascimento = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        LabelRG = new javax.swing.JLabel();
        TextRG = new javax.swing.JTextField();
        LabelCEP = new javax.swing.JLabel();
        TextCEP = new javax.swing.JTextField();
        ButtonCancel = new javax.swing.JButton();
        TextEndereco = new javax.swing.JTextField();
        LabelDadosCliente = new javax.swing.JLabel();
        ButtonCofirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelIDCliente = new javax.swing.JLabel();
        TextIDCliente = new javax.swing.JTextField();
        RadioButtonClienteOuro = new javax.swing.JRadioButton();
        LabelCategoriaCNH = new javax.swing.JLabel();
        ComboBoxCategoriaCNH = new javax.swing.JComboBox<>();
        TextNumeroCNH = new javax.swing.JTextField();
        LabelNumeroCNH = new javax.swing.JLabel();
        TextDiaCNH = new javax.swing.JTextField();
        LabelValidadeCNH = new javax.swing.JLabel();
        LabelDadosCNH = new javax.swing.JLabel();
        TextMesCNH = new javax.swing.JTextField();
        TextAnoCNH = new javax.swing.JTextField();
        TextMesNascimento = new javax.swing.JTextField();
        TextAnoNascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PanelCadastrarCliente.setBackground(new java.awt.Color(255, 255, 255));

        LabelNome.setText("Nome");

        TextNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNome.setMinimumSize(null);

        LabelCPF.setText("CPF");

        TextCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCPF.setMinimumSize(null);

        LabelDataNascimento.setText("Data de Nasciemento");

        TextDiaNascimento.setText("DD");
        TextDiaNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextDiaNascimento.setMinimumSize(null);
        TextDiaNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDiaNascimentoFocusGained(evt);
            }
        });
        TextDiaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDiaNascimentoActionPerformed(evt);
            }
        });

        LabelEmail.setText("Email");

        TextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEmail.setMinimumSize(null);

        LabelEndereco.setText("Endereço");

        LabelRG.setText("RG");

        TextRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextRG.setMinimumSize(null);

        LabelCEP.setText("CEP");

        TextCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCEP.setMinimumSize(null);
        TextCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCEPActionPerformed(evt);
            }
        });

        ButtonCancel.setBackground(new java.awt.Color(229, 4, 4));
        ButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setText("Cancelar");
        ButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCancel.setBorderPainted(false);
        ButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCancel.setFocusable(false);
        ButtonCancel.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setRequestFocusEnabled(false);
        ButtonCancel.setRolloverEnabled(false);
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        TextEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        LabelDadosCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosCliente.setText("Dados do Cliente");
        LabelDadosCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonCofirm.setBackground(new java.awt.Color(37, 149, 3));
        ButtonCofirm.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCofirm.setText("Confirmar");
        ButtonCofirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCofirm.setBorderPainted(false);
        ButtonCofirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCofirm.setFocusable(false);
        ButtonCofirm.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setRequestFocusEnabled(false);
        ButtonCofirm.setRolloverEnabled(false);
        ButtonCofirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCofirmActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(32, 32, 32));

        LabelIDCliente.setText("Código do Cliente");

        TextIDCliente.setEditable(false);
        TextIDCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextIDCliente.setMinimumSize(null);

        RadioButtonClienteOuro.setText("Cliente de Ouro");
        RadioButtonClienteOuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonClienteOuroActionPerformed(evt);
            }
        });

        LabelCategoriaCNH.setText("Categoria CNH");

        ComboBoxCategoriaCNH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        ComboBoxCategoriaCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaCNHActionPerformed(evt);
            }
        });

        TextNumeroCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNumeroCNH.setMinimumSize(null);

        LabelNumeroCNH.setText("Número CNH");

        TextDiaCNH.setText("DD");
        TextDiaCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextDiaCNH.setMinimumSize(null);
        TextDiaCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDiaCNHFocusGained(evt);
            }
        });
        TextDiaCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDiaCNHActionPerformed(evt);
            }
        });

        LabelValidadeCNH.setText("Validade CNH");

        LabelDadosCNH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosCNH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosCNH.setText("Dados da CNH");
        LabelDadosCNH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TextMesCNH.setText("MM");
        TextMesCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMesCNH.setMinimumSize(null);
        TextMesCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextMesCNHFocusGained(evt);
            }
        });

        TextAnoCNH.setText("AAAA");
        TextAnoCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoCNH.setMinimumSize(null);
        TextAnoCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAnoCNHFocusGained(evt);
            }
        });

        TextMesNascimento.setText("MM");
        TextMesNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMesNascimento.setMinimumSize(null);
        TextMesNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextMesNascimentoFocusGained(evt);
            }
        });
        TextMesNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMesNascimentoActionPerformed(evt);
            }
        });

        TextAnoNascimento.setText("AAAA");
        TextAnoNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoNascimento.setMinimumSize(null);
        TextAnoNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAnoNascimentoFocusGained(evt);
            }
        });
        TextAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAnoNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastrarClienteLayout = new javax.swing.GroupLayout(PanelCadastrarCliente);
        PanelCadastrarCliente.setLayout(PanelCadastrarClienteLayout);
        PanelCadastrarClienteLayout.setHorizontalGroup(
            PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextEndereco)
                                    .addComponent(LabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                                .addComponent(TextDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TextAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDadosCNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TextNumeroCNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LabelNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(LabelValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                                .addComponent(TextDiaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TextMesCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TextAnoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(RadioButtonClienteOuro))
                                .addGap(0, 355, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        PanelCadastrarClienteLayout.setVerticalGroup(
            PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarClienteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LabelIDCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDadosCliente)
                    .addComponent(LabelDadosCNH))
                .addGap(18, 18, 18)
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelCategoriaCNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCPF)
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelNumeroCNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCadastrarClienteLayout.createSequentialGroup()
                        .addComponent(LabelValidadeCNH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextDiaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextMesCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextAnoCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonClienteOuro)
                .addGap(7, 7, 7)
                .addGroup(PanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void ButtonCofirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCofirmActionPerformed
        // TODO add your handling code here:
        String nome = TextNome.getText();
        String cpf = TextCPF.getText();
        String rg = TextRG.getText();
        String cep = TextCEP.getText();
        String endereco = TextEndereco.getText();
        String email = TextEmail.getText();
        String categoriaCNH = (String)ComboBoxCategoriaCNH.getSelectedItem();
        String numeroCNH = TextNumeroCNH.getText();
        boolean clienteOuro = RadioButtonClienteOuro.isSelected();
        
        String diaNascimento = TextDiaNascimento.getText();
        String mesNascimento = TextMesNascimento.getText();
        String anoNascimento = TextAnoNascimento.getText();

        String diaCNH = TextDiaCNH.getText();
        String mesCNH = TextMesCNH.getText();
        String anoCNH = TextAnoCNH.getText();
        
        String[] itens = {
        nome,
        cpf,
        rg,
        cep,
        endereco,
        email,
        diaNascimento,
        mesNascimento, 
        anoNascimento,
        categoriaCNH, 
        numeroCNH,
        diaCNH,
        mesCNH,
        anoCNH
        };
        
        if(!Utilidades.hasNull(itens)){
            Calendar dataNascimento = Utilidades.getValidDate(diaNascimento, mesNascimento, anoNascimento);
            Calendar validadeCNH = Utilidades.getValidDate(diaCNH, mesCNH, anoCNH);
            
            if(dataNascimento != null && validadeCNH != null){
                
                try {
                Usuario f = new Cliente(
                    this.id,
                    nome,
                    cpf,
                    rg, 
                    dataNascimento, 
                    endereco, 
                    cep, 
                    email, 
                    categoriaCNH, 
                    numeroCNH,
                    validadeCNH,
                    clienteOuro);

                controller.addUsuario(f);
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado."
                        + " Cliente cadastrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                } catch(NumberFormatException nfe){
                    System.out.println(nfe);

                    JOptionPane.showMessageDialog(this, "Dados inválidos."
                        + " Entradas para salário devem ter o formato: 1111.111,"
                        + " e entradas de data devem ser valores inteiros!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
                } //tryCatch
            } //if validDate
            else {
                JOptionPane.showMessageDialog(this, "Data inválida."
                        + " Dia, mês ou ano inserido são inválidos!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } //if hasNull
        else {
            JOptionPane.showMessageDialog(this, "Entrada de dado vazia."
                    + " Por favor preencha todos os campos!",
                "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonCofirmActionPerformed

    private void RadioButtonClienteOuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonClienteOuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonClienteOuroActionPerformed

    private void TextDiaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDiaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDiaNascimentoActionPerformed

    private void TextCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCEPActionPerformed

    private void ComboBoxCategoriaCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCategoriaCNHActionPerformed

    private void TextDiaCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDiaCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDiaCNHActionPerformed

    private void TextDiaCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDiaCNHFocusGained
        // TODO add your handling code here:
        if(TextDiaCNH.getText().equals("DD")){
            TextDiaCNH.setText("");
        }
    }//GEN-LAST:event_TextDiaCNHFocusGained

    private void TextMesCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextMesCNHFocusGained
        // TODO add your handling code here:
        if(TextMesCNH.getText().equals("MM")){
            TextMesCNH.setText("");
        }
    }//GEN-LAST:event_TextMesCNHFocusGained

    private void TextAnoCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAnoCNHFocusGained
        // TODO add your handling code here:
        if(TextAnoCNH.getText().equals("AAAA")){
            TextAnoCNH.setText("");
        }
    }//GEN-LAST:event_TextAnoCNHFocusGained

    private void TextMesNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMesNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMesNascimentoActionPerformed

    private void TextAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAnoNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAnoNascimentoActionPerformed

    private void TextAnoNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAnoNascimentoFocusGained
        // TODO add your handling code here:
        if(TextAnoNascimento.getText().equals("AAAA")){
            TextAnoNascimento.setText("");
        }
    }//GEN-LAST:event_TextAnoNascimentoFocusGained

    private void TextMesNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextMesNascimentoFocusGained
        // TODO add your handling code here:
        if(TextMesNascimento.getText().equals("MM")){
            TextMesNascimento.setText("");
        }
    }//GEN-LAST:event_TextMesNascimentoFocusGained

    private void TextDiaNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDiaNascimentoFocusGained
        // TODO add your handling code here:
        if(TextDiaNascimento.getText().equals("DD")){
            TextDiaNascimento.setText("");
        }
    }//GEN-LAST:event_TextDiaNascimentoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarCliente dialog = new CadastrarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCofirm;
    private javax.swing.JComboBox<String> ComboBoxCategoriaCNH;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCategoriaCNH;
    private javax.swing.JLabel LabelDadosCNH;
    private javax.swing.JLabel LabelDadosCliente;
    private javax.swing.JLabel LabelDataNascimento;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelIDCliente;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumeroCNH;
    private javax.swing.JLabel LabelRG;
    private javax.swing.JLabel LabelValidadeCNH;
    private javax.swing.JPanel PanelCadastrarCliente;
    private javax.swing.JRadioButton RadioButtonClienteOuro;
    private javax.swing.JTextField TextAnoCNH;
    private javax.swing.JTextField TextAnoNascimento;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextDiaCNH;
    private javax.swing.JTextField TextDiaNascimento;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextIDCliente;
    private javax.swing.JTextField TextMesCNH;
    private javax.swing.JTextField TextMesNascimento;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNumeroCNH;
    private javax.swing.JTextField TextRG;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
