
package views;

import Controller.Controller;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import models.Cliente;
import models.Locacao;
import models.Veiculo;

/**
 *
 * @author karolyne Marques
 */
public class DevolucaoVeiculo extends javax.swing.JDialog {
    Controller controller = new Controller();
    ArrayList<Locacao> locacoes = controller.getLocacoes();
    ArrayList<Veiculo> veiculos = controller.getVeiculos();
    Veiculo veiculo = null;
    Locacao locacao = null;
    
    /**
     * Creates new form DevolucaoVeiculo
     */
    public DevolucaoVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDevolucaoVeiculo = new javax.swing.JPanel();
        LabelIDLocacao = new javax.swing.JLabel();
        TextIDLocacao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonCofirm = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        LabelModelo = new javax.swing.JLabel();
        TextModelo = new javax.swing.JTextField();
        LabelMontadora = new javax.swing.JLabel();
        TextMontadora = new javax.swing.JTextField();
        LabelCategoria = new javax.swing.JLabel();
        TextCategoria = new javax.swing.JTextField();
        LabelValorDiaria = new javax.swing.JLabel();
        TextValorFipe = new javax.swing.JTextField();
        LabelAnoFabricacao = new javax.swing.JLabel();
        TextAnoFabricacao = new javax.swing.JTextField();
        LabelAnoModelo = new javax.swing.JLabel();
        TextAnoModelo = new javax.swing.JTextField();
        LabelPlaca = new javax.swing.JLabel();
        TextPlaca = new javax.swing.JTextField();
        LabelDadosCarro = new javax.swing.JLabel();
        LabelDadosCliente = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        LabelCPF = new javax.swing.JLabel();
        LabelRG = new javax.swing.JLabel();
        TextCPF = new javax.swing.JTextField();
        TextRG = new javax.swing.JTextField();
        LabelCEP = new javax.swing.JLabel();
        TextCEP = new javax.swing.JTextField();
        LabelDataNascimento = new javax.swing.JLabel();
        TextDataNascimento = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        LabelCategoriaCNH = new javax.swing.JLabel();
        LabelNumeroCNH = new javax.swing.JLabel();
        TextNumeroCNH = new javax.swing.JTextField();
        LabelValidadeCNH = new javax.swing.JLabel();
        TextValidadeCNH = new javax.swing.JTextField();
        TextCategoriaCNH = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução de Veículo");
        setResizable(false);

        PanelDevolucaoVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        PanelDevolucaoVeiculo.setPreferredSize(new java.awt.Dimension(742, 524));

        LabelIDLocacao.setText("Código da Locação");

        TextIDLocacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 32, 32)));
        TextIDLocacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextIDLocacaoFocusLost(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(32, 32, 32));

        ButtonCofirm.setBackground(new java.awt.Color(37, 149, 3));
        ButtonCofirm.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCofirm.setText("Confirmar Devolução");
        ButtonCofirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCofirm.setBorderPainted(false);
        ButtonCofirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCofirm.setFocusable(false);
        ButtonCofirm.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCofirm.setRequestFocusEnabled(false);
        ButtonCofirm.setRolloverEnabled(false);
        ButtonCofirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCofirmActionPerformed(evt);
            }
        });

        ButtonCancel.setBackground(new java.awt.Color(229, 4, 4));
        ButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCancel.setText("Cancelar");
        ButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonCancel.setBorderPainted(false);
        ButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCancel.setFocusable(false);
        ButtonCancel.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonCancel.setRequestFocusEnabled(false);
        ButtonCancel.setRolloverEnabled(false);
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        LabelModelo.setText("Modelo");

        TextModelo.setEditable(false);
        TextModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextModelo.setMinimumSize(null);

        LabelMontadora.setText("Montadora");

        TextMontadora.setEditable(false);
        TextMontadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextMontadora.setMinimumSize(null);

        LabelCategoria.setText("Categoria");

        TextCategoria.setEditable(false);
        TextCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCategoria.setMinimumSize(null);

        LabelValorDiaria.setText("Valor Fipe");

        TextValorFipe.setEditable(false);
        TextValorFipe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextValorFipe.setMinimumSize(null);

        LabelAnoFabricacao.setText("Ano de Fabricação");

        TextAnoFabricacao.setEditable(false);
        TextAnoFabricacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoFabricacao.setMinimumSize(null);

        LabelAnoModelo.setText("Ano do Modelo");

        TextAnoModelo.setEditable(false);
        TextAnoModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextAnoModelo.setMinimumSize(null);

        LabelPlaca.setText("Placa");

        TextPlaca.setEditable(false);
        TextPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPlacaActionPerformed(evt);
            }
        });

        LabelDadosCarro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosCarro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosCarro.setText("Dados do Carro");
        LabelDadosCarro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelDadosCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelDadosCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDadosCliente.setText("Dados do Locador");
        LabelDadosCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LabelNome.setText("Nome");

        TextNome.setEditable(false);
        TextNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNome.setMinimumSize(null);

        LabelCPF.setText("CPF");

        LabelRG.setText("RG");

        TextCPF.setEditable(false);
        TextCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCPF.setMinimumSize(null);

        TextRG.setEditable(false);
        TextRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextRG.setMinimumSize(null);

        LabelCEP.setText("CEP");

        TextCEP.setEditable(false);
        TextCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCEP.setMinimumSize(null);
        TextCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCEPActionPerformed(evt);
            }
        });

        LabelDataNascimento.setText("Data de Nasciemento");

        TextDataNascimento.setEditable(false);
        TextDataNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextDataNascimento.setMinimumSize(null);
        TextDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDataNascimentoFocusGained(evt);
            }
        });
        TextDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataNascimentoActionPerformed(evt);
            }
        });

        LabelEndereco.setText("Endereço");

        TextEndereco.setEditable(false);
        TextEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        LabelEmail.setText("Email");

        TextEmail.setEditable(false);
        TextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextEmail.setMinimumSize(null);

        LabelCategoriaCNH.setText("Categoria CNH");

        LabelNumeroCNH.setText("Número CNH");

        TextNumeroCNH.setEditable(false);
        TextNumeroCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNumeroCNH.setMinimumSize(null);

        LabelValidadeCNH.setText("Validade CNH");

        TextValidadeCNH.setEditable(false);
        TextValidadeCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextValidadeCNH.setMinimumSize(null);
        TextValidadeCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextValidadeCNHFocusGained(evt);
            }
        });

        TextCategoriaCNH.setEditable(false);
        TextCategoriaCNH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextCategoriaCNH.setMinimumSize(null);
        TextCategoriaCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextCategoriaCNHFocusGained(evt);
            }
        });

        ButtonBuscar.setBackground(new java.awt.Color(32, 32, 32));
        ButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBuscar.setBorderPainted(false);
        ButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuscar.setFocusable(false);
        ButtonBuscar.setMaximumSize(new java.awt.Dimension(110, 30));
        ButtonBuscar.setMinimumSize(new java.awt.Dimension(110, 30));
        ButtonBuscar.setRequestFocusEnabled(false);
        ButtonBuscar.setRolloverEnabled(false);
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDevolucaoVeiculoLayout = new javax.swing.GroupLayout(PanelDevolucaoVeiculo);
        PanelDevolucaoVeiculo.setLayout(PanelDevolucaoVeiculoLayout);
        PanelDevolucaoVeiculoLayout.setHorizontalGroup(
            PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextIDLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelIDLocacao))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDevolucaoVeiculoLayout.createSequentialGroup()
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                            .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                            .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(LabelCategoriaCNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(TextCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36)
                                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(LabelValidadeCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                    .addComponent(TextValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelDadosCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextValorFipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextMontadora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                                .addComponent(LabelAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(LabelAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(LabelValorDiaria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelMontadora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                                .addComponent(TextAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(TextAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))))
        );
        PanelDevolucaoVeiculoLayout.setVerticalGroup(
            PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelIDLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextIDLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                        .addComponent(LabelDadosCliente)
                        .addGap(18, 18, 18)
                        .addComponent(LabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCPF)
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addComponent(LabelRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addComponent(LabelCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addComponent(LabelDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelValidadeCNH)))
                            .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextCategoriaCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextValidadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addComponent(LabelNumeroCNH))
                    .addGroup(PanelDevolucaoVeiculoLayout.createSequentialGroup()
                        .addComponent(LabelDadosCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelMontadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelValorDiaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextValorFipe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAnoFabricacao)
                            .addComponent(LabelAnoModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(LabelPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNumeroCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDevolucaoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonCofirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDevolucaoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelDevolucaoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearForm(){
        TextModelo.setText("");
        TextMontadora.setText("");
        TextCategoria.setText("");
        TextValorFipe.setText("");
        TextAnoFabricacao.setText("");
        TextAnoModelo.setText("");
        TextPlaca.setText("");

        TextNome.setText("");
        TextCPF.setText("");
        TextRG.setText("");
        TextCEP.setText("");
        TextEndereco.setText("");
        TextEmail.setText("");
        TextCategoriaCNH.setText("");
        TextNumeroCNH.setText("");
        TextValidadeCNH.setText("");
        TextDataNascimento.setText("");
        
        TextIDLocacao.setText("");
    }
    
    private void ButtonCofirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCofirmActionPerformed
        // TODO add your handling code here:
         this.veiculos.removeIf(v -> 
                 this.veiculo.getCodigoVeiculo() == v.getCodigoVeiculo());
         
         this.veiculo.devolver();
         
         this.veiculos.add(this.veiculo);
         controller.setVeiculos(this.veiculos);
         
         this.locacoes.removeIf(v -> 
                 this.locacao.getCodigoLocacao() == v.getCodigoLocacao());
         
         this.locacao.finalizar();
         
         this.locacoes.add(this.locacao);
         controller.setLocacoes(this.locacoes);
         
         JOptionPane.showMessageDialog(this, "Locação Finalizada!"
                        + " Veículo devolvido com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
         
         
    }//GEN-LAST:event_ButtonCofirmActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void TextCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCEPActionPerformed

    private void TextDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDataNascimentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataNascimentoFocusGained

    private void TextDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataNascimentoActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void TextValidadeCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextValidadeCNHFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValidadeCNHFocusGained

    private void TextIDLocacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIDLocacaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDLocacaoFocusLost

    private void TextCategoriaCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCategoriaCNHFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCategoriaCNHFocusGained

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // TODO add your handling code here:
        String id = TextIDLocacao.getText();
        
        if(!id.equals("")){
        
            this.locacao = controller.getLocacaoByCodigo(Integer.parseInt(id));

            if(this.locacao != null){
                
                this.veiculo = locacao.getVeiculoLocado();
                
                TextModelo.setText(this.veiculo.getNomeModelo());
                TextMontadora.setText(this.veiculo.getMontadora());
                TextCategoria.setText(this.veiculo.getCategoria());
                TextValorFipe.setText(Float.toString(this.veiculo.getValorDiaria()));
                TextAnoFabricacao.setText(Integer.toString(this.veiculo.getAnoFabricacao()));
                TextAnoModelo.setText(Integer.toString(this.veiculo.getAnoModelo()));
                TextPlaca.setText(this.veiculo.getPlaca());
                
                int idCliente = locacao.getCodigoCliente();
                Cliente c = controller.getClienteByCodigo(idCliente);
                
                TextNome.setText(c.getNome());
                TextCPF.setText(c.getCpf());
                TextRG.setText(c.getRg());
                TextCEP.setText(c.getCep());
                TextEndereco.setText(c.getEndereco());
                TextEmail.setText(c.getEmail());
                TextCategoriaCNH.setText(c.getCategoriaCNH());
                TextNumeroCNH.setText(c.getNumeroCNH());
                TextValidadeCNH.setText(c.getValidadeCNH().get(Calendar.DATE) 
                    + "-" + c.getValidadeCNH().get(Calendar.MONTH)
                    + "-" + c.getValidadeCNH().get(Calendar.YEAR));
                TextDataNascimento.setText(c.getDataNascimento().get(Calendar.DATE) 
                    + "-" + c.getDataNascimento().get(Calendar.MONTH)
                    + "-" + c.getDataNascimento().get(Calendar.YEAR));
            }
            else {
                JOptionPane.showMessageDialog(this, "Locação não encontrada!"
                        + " Verifique o código da locação.",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
                TextIDLocacao.requestFocus();
            }
        }
        else {
             JOptionPane.showMessageDialog(this, "Campo vazio!"
                        + " O campo código da Locação precisa ser preenchido.",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            TextIDLocacao.requestFocus();
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void TextPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolucaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolucaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolucaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolucaoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DevolucaoVeiculo dialog = new DevolucaoVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCofirm;
    private javax.swing.JLabel LabelAnoFabricacao;
    private javax.swing.JLabel LabelAnoModelo;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelCategoriaCNH;
    private javax.swing.JLabel LabelDadosCarro;
    private javax.swing.JLabel LabelDadosCliente;
    private javax.swing.JLabel LabelDataNascimento;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelIDLocacao;
    private javax.swing.JLabel LabelModelo;
    private javax.swing.JLabel LabelMontadora;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumeroCNH;
    private javax.swing.JLabel LabelPlaca;
    private javax.swing.JLabel LabelRG;
    private javax.swing.JLabel LabelValidadeCNH;
    private javax.swing.JLabel LabelValorDiaria;
    private javax.swing.JPanel PanelDevolucaoVeiculo;
    private javax.swing.JTextField TextAnoFabricacao;
    private javax.swing.JTextField TextAnoModelo;
    private javax.swing.JTextField TextCEP;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextCategoria;
    private javax.swing.JTextField TextCategoriaCNH;
    private javax.swing.JTextField TextDataNascimento;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextIDLocacao;
    private javax.swing.JTextField TextModelo;
    private javax.swing.JTextField TextMontadora;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNumeroCNH;
    private javax.swing.JTextField TextPlaca;
    private javax.swing.JTextField TextRG;
    private javax.swing.JTextField TextValidadeCNH;
    private javax.swing.JTextField TextValorFipe;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
